name: CI

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  cache-dependencies:
    name: Cache dependencies
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: wyvox/action-setup-pnpm@v3

  test-default:
    name: Test
    env:
      CI: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wyvox/action-setup-pnpm@v3
      - run: pnpm build
      - run: pnpm run test
        working-directory: ./test-app

  test-min-supported:
    name: Test min supported
    env:
      CI: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wyvox/action-setup-pnpm@v3
      - run: pnpm build
      - run: pnpm run test
        working-directory: ./test-app-min-supported

  test-min-supported-classic:
    name: Test min supported classic (non-embroider)
    env:
      CI: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wyvox/action-setup-pnpm@v3
      - run: pnpm build
      - run: pnpm run test
        working-directory: ./test-app-min-supported-classic

  ember-try:
    name: "Ember Try"
    env:
      CI: true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        try-scenario:
          [
            ember-lts-4.4,
            ember-lts-4.8,
            ember-lts-4.12,
            ember-lts-5.4,
            ember-lts-5.8,
            ember-release,
            ember-beta,
            ember-canary,
          ]
    steps:
      - uses: actions/checkout@v4
      - uses: wyvox/action-setup-pnpm@v3
      - run: pnpm build
      - run: node_modules/.bin/ember try:one ${{ matrix.try-scenario }} --skip-cleanup
        working-directory: ./test-app
        timeout-minutes: 10
